### ISSUE TITLE
fails when MPV too high

### ISSUE THREAD

**Issue by tissatussa** [KierenP/Halogen#266] opened 2021-02-24 10:51 UTC
hi, i discovered that all new v9 versions of Halogen which have MPV fail when MPV is higher than the amount of legal moves in the position .. eg. this FEN:  4R3/4k1p1/4p1Bp/3bN3/8/5PK1/3r2PP/4n3 b - - 7 46  has only 2 legal moves.

**Comment by KierenP** [comment] 2021-02-27 03:51
I've diagnosed the cause of this and think I have a good way to fix it. Should be fixed in the next few days

**Comment by tissatussa** [comment] 2021-02-27 08:58
i remember i discussed this very same bug with you a few months ago .. and then you easily solved it .. but now i'm not sure i recall this correctly, because i gather most older versions and they all still had this bug .. anyway, it must be easy to solve this error : just check the amount of legal moves in the position and set max MPV accordingly.

**Comment by KierenP** [comment] 2021-02-28 23:25
You remember correctly, but it seems my fix does not work for positions where the King is in check. I'll come up with a better solution soon

**Comment by KierenP** [comment] 2021-03-03 22:18
Fixed in https://github.com/KierenP/Halogen/pull/273

Please confirm this has fixed the issue for you and let me know if you spot any other bugs

**Comment by tissatussa** [comment] 2021-03-04 00:07
i just compiled your #273 and i found no errors of this kind : i tested a few in-check positions with different MPV and all seems OK.

**Comment by KierenP** [comment] 2021-03-04 00:43
Thank you for your quick response

**Closed by KierenP** 2021-03-04 00:43 UTC
